INSERT INTO USUARIO(nome) VALUES('Joao');
INSERT INTO USUARIO(nome) VALUES('Marcio');
INSERT INTO USUARIO(nome) VALUES('Aline');

INSERT INTO ANOTACAO(texto, titulo, data) VALUES ('PRIMEIRA ANOTACAO', 'TESTE DE ANOTACAO', '2019-05-05 20:00:00')
INSERT INTO ANOTACAO(texto, titulo, data) VALUES ('PRIMEIRA ANOTACAO', 'TESTE DE ANOTACAO', '2019-05-05 20:00:00')
INSERT INTO ANOTACAO(texto, titulo, data) VALUES ('PRIMEIRA ANOTACAO', 'TESTE DE ANOTACAO', '2019-05-05 20:00:00')
INSERT INTO ANOTACAO(texto, titulo, data) VALUES ('PRIMEIRA ANOTACAO', 'TESTE DE ANOTACAO', '2019-05-05 20:00:00')
INSERT INTO ANOTACAO(texto, titulo, data) VALUES ('PRIMEIRA ANOTACAO', 'TESTE DE ANOTACAO', '2019-05-05 20:00:00')

